### PR TITLE
add checkbox unit test

### PR DESCRIPTION
**Pull request by Thanood**
This PR adds some configuration for unit tests as well as a first unit test for checkbox.
There is also a fix for the `text` bindable which actually failed the test before fixing. 😃

### CODE REVIEW

**Comment by genadis** [comment]
@Thanood I appreciate your contribution!

Before I can accept it, please [sign our CLA](https://docs.google.com/forms/d/e/1FAIpQLSf2jn5cqBr2_ovLOGt3ars537Tu5s6TZ013QU6IJ-MsnEYuKg/viewform).

 We were using the components as part of our internal project, but decided to decouple it and release as open source in hopes it will help others...

I've noticed the major changes to package.json. I't probably because of formatting.. please make sure it's clean. Thanks!

**Comment by Thanood** [comment]
@genadis I have added `aurelia-framework` to `package.json` devDependencies but you already did that now. I will rebase my fork to reflect your changes.

I think (but I'm not sure) git committed the whole file because the line endings did not match your configuration in `.editorconfig`. And that may as well be my fault because I think my `npm` writes CRLF line endings. Sorry. Will update the PR.

**Comment by genadis** [comment]
Thanks!

**Comment by Thanood** [comment]
Rebased and signed the CLA. 😃 
If you're okay with the test setup I can add some more in the future.

**Comment by genadis** [comment]
Sounds good :)

I've squashed this pull request (11 commits because of the rebase to 1), but kept all your comments.
hope you don't mind...

**Comment by Thanood** [comment]
I don't. Thanks.

**Pull request merged**
